#!/bin/bash

usage () {
    echo "Usage: $0 -u <username> -p <password> -s <script name> -f <JSON file>"
    exit 1
}

while getopts ":u:p:f:s:" opt; do
  case $opt in
    u) USR=$OPTARG;;
    p) PW=$OPTARG;;
    s) name=$OPTARG;;
    f) jsonFile=$OPTARG;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      ;;
  esac
done

if [ -z "$USR" ]; then usage; fi
if [ -z "$PW" ]; then usage; fi
if [ -z "$name" ]; then usage; fi
if [ -z "$jsonFile" ]; then usage; fi

printf "Updating Integration API Script $name with $jsonFile\n\n"

curl -v -X PUT -u $USR:$PW --header "Content-Type: application/json" "http://localhost:$NEXUS_PORT/service/rest/v1/script/$name" -d @$jsonFile
