#!/bin/bash

usage () {
    echo "Usage: $0 -u <username> -p <password>"
    exit 1
}

while getopts ":u:p:" opt; do
  case $opt in
    u) USR=$OPTARG;;
    p) PW=$OPTARG;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      ;;
  esac
done

if [ -z "$USR" ]; then usage; fi
if [ -z "$PW" ]; then usage; fi

printf "Listing Integration API Scripts\n"

curl -v -u $USR:$PW 'http://localhost:8081/service/rest/v1/script'
