version: '3'

networks:
  devopsnetwork:
    external: true

volumes:
  jenkins-data:
  postgres-data:
  nexus-data:
  shared-data:
  maven-repo:

services:
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "18080:8080"
    networks:
      - devopsnetwork
    volumes:
      - ${MY_REPOS}:/repos
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - maven-repo:/root/.m2
    depends_on:
      - sonar
    environment:
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
  sonardb:
    build: ./sonardb
    networks:
      - devopsnetwork
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  sonar:
    build: ./sonar
    restart: always
    ports:
      - "19000:9000"
      - "19092:9092"
    networks:
      - devopsnetwork
    depends_on:
      - sonardb
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonardb:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
  nexus:
    build: ./nexus
    restart: always
    ports:
      - "8400:8400"
      - "8401:8401"
      - "8500:8500"
      - "8501:8501"
    volumes:
      - nexus-data:/nexus-data
      - shared-data:/shared-data
    networks:
      - devopsnetwork
