#!/bin/bash

# The following env vars should be defined by the source image
echo "===================================================="
echo "Sonar environment"
echo "----------------------------------------------------"
echo "SONARQUBE_HOME : ${SONARQUBE_HOME}"
echo "SONAR_VERSION  : ${SONAR_VERSION}"
echo "SONAR_PORT     : ${SONAR_PORT}"
echo "----------------------------------------------------"
echo "PATH           : ${PATH}"
echo "===================================================="

# Zero out log file
cat /dev/null > $STARTUP_LOG

echo "Launching SonarQube ..." >> $STARTUP_LOG
nohup ${SONARQUBE_HOME}/bin/run.sh &

# Wait for SonarQube to come up ...
SONAR_UP=200
SONAR_STATE=999
SONAR_DELAY=5

# Yes, we are deliberately waiting at least SONAR_DELAY seconds to give the server time to get its act together
echo "======================================" >> $STARTUP_LOG
echo "Waiting for SonarQube API to come up ..."       >> $STARTUP_LOG
echo "--------------------------------------" >> $STARTUP_LOG
while [ "$SONAR_STATE" -ne "$SONAR_UP" ]; do
    echo "SonarQube API is not up yet ... :(" >> $STARTUP_LOG
    sleep $SONAR_DELAY
    SONAR_STATE=$(curl -s -o /dev/null -w "%{http_code}" "http://sonar:$SONAR_PORT/api/server/version")
done
echo "--------------------------------------" >> $STARTUP_LOG
echo "SonarQube API is up ... :)"                     >> $STARTUP_LOG
echo "======================================" >> $STARTUP_LOG
sleep $SONAR_DELAY

# Set up a WebHook for Jenkins
curl "http://$SONAR_USR:$SONAR_PW@sonar:$SONAR_PORT/api/webhooks/create" -X POST -d "name=jenkins&url=http://jenkins:8080/sonarqube-webhook/" >> $STARTUP_LOG

# Since we nohup'd the main SonarQube process, we need to keep the container alive using this script
tail -f /dev/null